name: floating_navbar
description: Customisable, clean looking bottom floating  navbar. FloatingNavBar comes with multiple customization options - colors, page indicators, etc. This can be used as an alternative to the default BottomNavigationBar
version: 2.0.1+1
homepage: https://www.iamngoni.co.zw/floating_navbar

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
