name: floating_navbar
description: A new Flutter package project.
version: 1.0.0
author: Ngonidzashe Mangudya
homepage: www.iamngoni.co.zw/floating_navbar

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
