name: floating_navbar
description: Customisable bottom floating  navbar.
version: 1.1.0
homepage: https://www.iamngoni.co.zw/floating_navbar

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
